name: native_scroll
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/tomgilder/native_scroll

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.6"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
